lobby:
  world: world
  location:
    x: 0
    y: 0
    z: 0
minigames:
  ColorMatch:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  Spleef:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  MineField:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    finishline:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 95
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  JumpnRun:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    finishline:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  DeadEnd:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  RedAlert:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  LastArcherStanding:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  SheepFreenzy:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  SmokeMonster:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    lobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    enabled: false
  SlapFight:
    spawn:
      world: world
      location:
        x: 0
        y: 0
        z: 0
    spectatorlobby:
      world: world
      location:
        x: 0
        y: 0
        z: 0