config:
  auto_updating: true
  min_players: 1
  game-on-join: false
  max_reward: 30
  min_reward: 10
  use_economy: false
  use_item_rewards: false
  item_reward_maxamount: 10
  item_reward_minamount: 3
  item_reward_id: 264
  max_players: 50
  scoreboardoutgame: true
  announcements: true
  seconds_for_each_minigame: 60
shop:
  grenades_price: 70
  jumpboost_price: 60
  deadendboost_price: 50
  chickentagboost_price: 60
  slapfight_knockback_price: 100
  smokemonsterboost_price: 150
  jumpnrunboost_price: 150
  sheepfreenzyimmunity_price: 100
  megagrenades_price: 130